# Edit basic info about your site here
url: 'http://example.com'
baseurl: '/online-cv' #change it according to your repository name

title: My Resume
description: my beautiful online resume

# You can enable google analytics here
#google_analytics: UA-XXXXXX-XXXXXX

# Enable one of these styles by removing #.
# Style will be applied only after restarting the build or serve.
style: styles
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

# What's next ?
# Update all the sections by editing the files inside _data folder.
